name: Code Analysis
on: [ push, pull_request ]

jobs:
    coding-standards:
        name: Coding Standards
        runs-on: 'ubuntu-latest'

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install PHP Dependencies
                run: composer update

            -   name: Verify Coding Standards
                run: composer run format

            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Apply php-cs-fixer changes

